# hadolint ignore=DL3007
FROM opensuse/tumbleweed:latest

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV TERM=xterm-256color

# --- Update system and install packages ---

# Install base KDE Plasma Wayland desktop from official repos
# hadolint ignore=DL3037
RUN zypper --non-interactive install -t pattern kde kde_plasma && \
    zypper install -y --no-recommends \
        wget \
        perl \
        firefox-esr \
        konsole \
        dolphin \
        libcap-progs \
        dbus-1-daemon \
        pipewire-pulseaudio \
        xorg-x11-server \
        xorg-x11 xhost \
        kdeplasma6-addons \
        vulkan-tools \
        libvulkan1 \
        libvulkan_radeon \
        libvulkan_radeon-32bit \
        libvulkan_intel \
        libvulkan_intel-32bit \
        plasma6-session \
        xwayland \
        discover \
        polkit-kde-agent-6 \
        pipewire plasma6-pa \
        libva-drm2 \
        protontricks \
        sudo seatd dbus-1 google-noto-sans-cjk-fonts

RUN zypper --non-interactive install -y boost-devel libminiupnpc21 \
    libboost_log-devel \
    libboost_program_options-devel

# Patch for sunsine
RUN ln -sf /usr/lib64/libboost_log.so /usr/lib64/libboost_log.so.1.91.0 && \
    ln -sf /usr/lib64/libboost_program_options.so /usr/lib64/libboost_program_options.so.1.91.0 && \
    ln -sf /usr/lib64/libboost_filesystem.so.1.92.0 /usr/lib64/libboost_filesystem.so.1.91.0 && \
    ln -sf /usr/lib64/libboost_thread.so /usr/lib64/libboost_thread.so.1.91.0


# Install NVIDIA utilities from OBS repository (optional)
ARG GPU=NVIDIA
ARG NVIDIA_DRIVER_VERSION=615.71.09

COPY pkg/opensuse-nvidia.sh /tmp/nvidia.sh
RUN chmod +x /tmp/nvidia.sh && \
    ./tmp/nvidia.sh

# Add gaming tools repository and install additional packages (optional)
# hadolint ignore=DL3037
RUN zypper install -y --auto-agree-with-licenses nvtop mangohud steam

# Add the sunshine repository and install sunshine (optional)
RUN zypper addrepo  https://download.opensuse.org/repositories/games:/tools/openSUSE_Tumbleweed/games:tools.repo && \
    zypper --non-interactive --gpg-auto-import-keys up
RUN zypper --non-interactive install -y libboost_filesystem*-devel &&\
    zypper --pkg-cache-dir /tmp download sunshine

RUN rpm -i --nodeps /tmp/games_tools/x86_64/*.rpm && \
    rm -rf /tmp/games_tools

# Clean pkg
RUN zypper clean -a

# Configure locale for openSUSE Tumbleweed
RUN echo "LANG=en_US.UTF-8" > /etc/locale.conf \
    && echo "en_US.UTF-8 UTF-8" >> /etc/sysconfig/language \
    && echo "KEYMAP=us" > /etc/vconsole.conf

# --- Non-root user to run the session ---
RUN groupadd -g 1000 kde && \
    groupadd -g 948 seat && \
    useradd -u 1000 -g 1000 -m -G video,render,input,seat,kde -s /bin/bash kde && \
    echo "kde ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/kde 

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /home/kde
# Init config dir for kde desktop and steam, and chown to kde user
RUN mkdir -p /home/kde/.mozilla/firefox \
    /home/kde/.local/state/wireplumber \
    /home/kde/.config/dconf \
    /home/kde/.fontconfig \
    /home/kde/.cache/fontconfig \
    /run/user/1000 /run/dbus && \
    mkdir -p /tmp/.X11-unix && \
    chmod -R 1777 /tmp/.X11-unix    

RUN chown -R kde:kde /home/kde /run/user/1000 /run/dbus && \
    chmod 700 /run/user/1000 

USER 1000:1000
COPY <<"EOF" /home/kde/.local/share/konsole/DefaultProfile.profile
[General]
Name=DefaultProfile
Parent=FALLBACK/
Command=/bin/bash
EOF

CMD ["/usr/local/bin/entrypoint.sh"]
