apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genshin-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 150G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zzz-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 90G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endfield-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 65G
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warthunder-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 65G