apiVersion: v1
kind: ConfigMap
metadata:
  name: sunshine-config
  namespace: {{ .Values.namespace }}
  labels:
    app: sunshine
data:
  sunshine.conf: |
    origin_web_ui_allowed = wan
    csrf_allowed_origins = {{- range until (.Values.replicaCount | int) }} https://matahari-kde-{{ . }}.matahari-desktop.{{ $.Values.namespace }}.svc.cluster.local:47990{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mangohud-config
  namespace: {{ .Values.namespace }}  
  labels:
    app: sunshine
data:
  MangoHud.conf: | {{ .Values.configMap.MangoHud | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: non-steam-bootstrap
  namespace: {{ .Values.namespace }}  
  labels:
    app: sunshine
data:
  non_steam.sh: |-
    #!/bin/sh
    wget -q --show-progress https://github.com/cameronhimself/nonsteam/releases/download/0.7.0/nonsteam-linux-x64-0.7.0.tar.gz \
      -O /tmp/nonsteam-linux-x64-0.7.0.tar.gz
    cd /tmp
    tar -zxf nonsteam-linux-x64-0.7.0.tar.gz
    cd nonsteam-linux-x64-0.7.0
    {{ .Values.configMap.steamBootstrap | nindent 4 }}
