service:
    secret:
        desktopPassword: ENC[AES256_GCM,data:p1f74bc6za4o,iv:szcHww9TDzj6VbzRe12VZfit0oZHM3hSfUujvz7gMAo=,tag:d0hKJCjv8OuuTGrfx4Z5GA==,type:str]
sops:
    lastmodified: "2026-08-18T08:54:26Z"
    mac: ENC[AES256_GCM,data:hDFr3YpHbYMMYIFvruaEjq714yXWl4XfTpqXfll08L0tQNBaIxNTv5xzUSM07auzBFDtveF6MhopZFWFnNeC3QJIvoVkQkKwhj4QNWE8gz0P5l+J50yFxssdg2mEYN9ktQ/Peg8iee+dIiNjb7ZQWylgb9ZLQytavvUGefOn5AQ=,iv:xw1Tx9qZ74M/dPTBJnEnpxoORY4rdFFJrA7ez6YcDZk=,tag:9K4fj2lthWPHLOnD156MHA==,type:str]
    pgp:
        - created_at: "2026-08-18T08:23:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D0zPJ0Kvui3MSAQdAqDAZoHEKveo/SCnFkCsA0xbxzzlOE13ltRA1HnBpTnAw
            a4Xmo2NKE8R6Q9IECQ/k3hZRosd5GJZk8WbqrI72mBONhbNZ/5keolNNtT3rWNAd
            0lwB2YAhP4b3DKjh3MplhcdxP+uDPUpGh0ea7OsU+RT56X0IszSU6scxFzJkLMm+
            PY4n/zvqAe5cBZBtKDkTvZfJvE8T8Gc2j9D6djEJ4GdPDWDyxB7iCS+9dyFY/w==
            =/bf9
            -----END PGP MESSAGE-----
          fp: BCC9CAF551FF48C51849F84FA81094A27AF621CC
    unencrypted_suffix: _unencrypted
    version: 3.13.3
