name: Dockerfile Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'Dockerfile.archlinux'
      - 'Dockerfile.opensuse'
      - '.github/workflows/image-linter.yml'

jobs:
  lint-dockerfiles:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - Dockerfile.archlinux
          - Dockerfile.opensuse

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint ${{ matrix.dockerfile }}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
